import type { Metadata } from "next";
import { Inter, Recursive } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
import Provider from "@/components/Provider";

const recursive = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "cobra cover",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={recursive.className}>
        <NavBar />
        <main className="flex flex-col grainy-light min-h-[calc(100vh-3.5rem-1px)]">
          <div className="flex-1 flex flex-col h-full">
            <Provider>
              {children}
            </Provider>
          </div>
          <Footer />
        </main>

        <Toaster />
      </body>
    </html>
  );
}
